# modus-vivendi (Dark theme)
key_bindings:
  - { key: Y, mods: Control, action: Paste }
  # - { key: G,  mods: Control, mode: ~Search,    action: ToggleViMode            }
  # - { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom          }

  # - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
  # - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
font:
  normal:
    family: Sarasa Term SC Nerd
    style: Regular

  bold:
    family: Sarasa Term SC Nerd
    style: Bold

  italic:
    family: Sarasa Term SC Nerd
    style: Italic

  bold_italic:
    family: Sarasa Term SC Nerd
    style: Bold Italic

  size: 15

# font:
#   normal:
#     family: Monaco
#     style: Regular

#   bold:
#     family: Monaco
#     style: Bold

#   italic:
#     family: Monaco
#     style: Italic

#   bold_italic:
#     family: Monaco
#     style: Bold Italic

#   size: 15
env:
  TERM: xterm-256color
colors:
  primary:
    background: "#1f1f1f"
    foreground: "#eeeeeb"
  # Bright and dim foreground colors
    dim_foreground: "#1e1e1e"
    bright_foreground: "#ffffff"
  # Normal colors
  normal:
    black:   "#616161"
    red:     "#ff8272"
    green:   "#b4fa72"
    yellow:  "#fefdc2"
    blue:    "#a5d5fe"
    magenta: "#ff8ffd"
    cyan:    "#d0d1fe"
    white:   "#f1f1f1"
  # Bright colors
  bright:
    black:   "#8e8e8e"
    red:     "#ffc4bd"
    green:   "#d6fcb9"
    yellow:  "#fefdd5"
    blue:    "#c1e3fe"
    magenta: "#ffb1fe"
    cyan:    "#e5e6fe"
    white:   "#feffff"
  # Dim colors
  dim:
    black:   "#000000"
    red:     "#ff9580"
    green:   "#88ca9f"
    yellow:  "#d2b580"
    blue:    "#82b0ec"
    magenta: "#caa6df"
    cyan:    "#9ac8e0"
    white:   "#989898"
