# modus-vivendi (Dark theme)
key_bindings:
  - { key: Y, mods: Control, action: Paste }
  # C-2 with xremap to C-Shift-space
  # - { key: V, mods: Shift|Control, action: ToggleViMode }
  - { key: Escape,   mode: Vi, action: ToggleViMode          }
  - { key: G,mods: Control,   mode: Vi, action: ToggleViMode          }
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance } # spacebar+return

  # - { key: Space,  mods: Shift|Control, mode: Vi|~Search, action: ScrollToBottom          }

  # - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
  # - { key: Space,  mods: Shift|Control, mode: ~Search,    action: ToggleViMode            }
font:
  normal:
#     family: Monaco
    family: Sarasa Term SC Nerd
    style: Regular

  bold:
    family: Sarasa Term SC Nerd
    style: Bold

  italic:
    family: Sarasa Term SC Nerd
    style: Italic

  bold_italic:
    family: Sarasa Term SC Nerd
    style: Bold Italic

  size: 15
env:
  TERM: xterm-256color
colors:
  primary:
    background: '0x111111'
    foreground: '0xdcdccc'
    # dim_foreground: "#1e1e1e"
    # bright_foreground: "#ffffff"
  normal:
    black:   '0x222222'
    red:     '0xcc9393'
    green:   '0x7f9f7f'
    yellow:  '0xd0bf8f'
    blue:    '0x6ca0a3'
    magenta: '0xdc8cc3'
    cyan:    '0x93e0e3'
    white:   '0xdcdccc'
  bright:
    black:   '0x666666'
    red:     '0xdca3a3'
    green:   '0xbfebbf'
    yellow:  '0xf0dfaf'
    blue:    '0x8cd0d3'
    magenta: '0xfcace3'
    cyan:    '0xb3ffff'
    white:   '0xffffff'
  dim:
    black:   "#000000"
    red:     "#ff9580"
    green:   "#88ca9f"
    yellow:  "#d2b580"
    blue:    "#82b0ec"
    magenta: "#caa6df"
    cyan:    "#9ac8e0"
    white:   "#989898"
