# modus-vivendi (Dark theme)
# key_mappings:

font:
  normal:
    family: Monaco
    style: Regular

  bold:
    family: Monaco
    style: Bold

  italic:
    family: Monaco
    style: Italic

  bold_italic:
    family: Monaco
    style: Bold Italic

  size: 11
  size: 15
env:
  TERM: xterm-256color
colors:
  primary:
    background: "#000000"
    foreground: "#ffffff"
  # Bright and dim foreground colors
    dim_foreground: "#1e1e1e"
    bright_foreground: "#ffffff"
  # Normal colors
  normal:
    black:   "#000000"
    red:     "#ff5f59"
    green:   "#44bc44"
    yellow:  "#d0bc00"
    blue:    "#2fafff"
    magenta: "#feacd0"
    cyan:    "#00d3d0"
    white:   "#ffffff"
  # Bright colors
  bright:
    black:   "#000000"
    red:     "#ff5f5f"
    green:   "#44df44"
    yellow:  "#efef00"
    blue:    "#338fff"
    magenta: "#ff66ff"
    cyan:    "#9ac8e0"
    white:   "#ffffff"
  # Dim colors
  dim:
    black:   "#000000"
    red:     "#ff9580"
    green:   "#88ca9f"
    yellow:  "#d2b580"
    blue:    "#82b0ec"
    magenta: "#caa6df"
    cyan:    "#9ac8e0"
    white:   "#989898"
